### ISSUE TITLE
erro no arquivo templates/new_topic.html form.as_p nao renderiza as entradas do form

### ISSUE THREAD

**Issue by ettoreleandrotognoli** [cesartalves/begginer-django-guide-complete#1]
Na vdd o erro é aqui:
https://github.com/cesartalves/begginer-django-guide-complete/blob/32f53fb9ed4a369d7e8df530ced3abfd818004e7/boards/views.py#L44

Você precisa passar o form para o template, o terceiro paramento, o dicionário, é o contexto do template.
Você pode escrever algo como:
```python
return render(request,'new_topic.html',{'board':board,'form':form})
```
Ou se você preferir (eu prefiro) usar o método [locals](https://docs.python.org/2/library/functions.html#locals).
```python
return render(request,'new_topic.html',locals())
```

**Comment by cesartalves** [comment]
Opa, era mesmo! Deu certo aqui :)
